##日志
logging:
  config: classpath:logback-dev.xml
spring:
  datasource:
    url: jdbc:mysql://172.24.2.13:3306/nbtd?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: admin
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
