##日志
logging:
  config: classpath:logback-dev.xml
spring:
  datasource:
    url: jdbc:mysql://47.118.194.10:3306/wechat_mini_program
    username: anx
    password: Ax@12345
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
